language: c

os: linux
dist: trusty
sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tools/apt-get-install-deps.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tools/apt-get-install-qemu-arm.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tools/brew-install-deps.sh; fi

install:

script: "python tools/run-tests.py $OPTS"

env:
  - OPTS="--check-signed-off --check-cppcheck --check-vera"
  - OPTS="--jerry-tests --jerry-test-suite"
  - OPTS="--jerry-tests --jerry-test-suite --toolchain=cmake/toolchain_linux_armv7l.cmake" TIMEOUT=300
  - OPTS=--buildoption-test
  - OPTS=--unittests

matrix:
  include:
    - os: osx
      env: OPTS="--jerry-tests --jerry-test-suite"
    - os: osx
      env: OPTS=--unittests
